### PR TITLE
Fix issue "The given key 'queryData' was not present in the dictionary" and authMode

### PR DESCRIPTION
**Pull request by PeterKvayt**
Hi!

This pr is intended to fix this [issue](https://github.com/umbraco/Umbraco.Commerce.PaymentProviders.Worldpay/issues/4).

Fix implemented in 51539a9af87b5485fa75b233835df6e77fffeec6 commit.

The 576c128cbcef51d3715bab9fb3040c5372c68546 commit is refactoring.

During refactoring revealed some interesing things: 

- [issue with authMode](https://github.com/umbraco/Umbraco.Commerce.PaymentProviders.Worldpay/issues/5)
- [issue with status codes](https://github.com/umbraco/Umbraco.Commerce.PaymentProviders.Worldpay/issues/7)

@mattbrailsford Could you please review this pr and related issues?

### CODE REVIEW

**Comment by PeterKvayt** [comment]
@mattbrailsford 

Could you please review the pipeline, I can see the original reason why it failed.

**Comment by umbracotrd** [comment]
Hello @PeterKvayt,

Thank you for taking your time to investigate the issue and create this PR.

We have a pipeline task to detect breaking changes in the PRs. For this particular one, the pipeline is complaining about the breaking changes you made in this PR, for example, removing properties in `WorldpayBusinessGateway350Settings.cs`. Those changes violate our [versioning strategy](https://docs.umbraco.com/welcome/documentation-and-versions). I suggest that instead of removing those properties/classes, you should mark them as `[Obsolete("with a meaningful message"]` and we will remove them in the incoming major version.

```
/opt/hostedtoolcache/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets(37,5): error CP0002: Member 'Umbraco.Commerce.PaymentProviders.Worldpay.WorldpayBusinessGateway350Settings.InstallId.get' exists on [Baseline] lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll but not on lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll [/home/vsts/work/1/s/src/Umbraco.Commerce.PaymentProviders.Worldpay/Umbraco.Commerce.PaymentProviders.Worldpay.csproj]
/opt/hostedtoolcache/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets(37,5): error CP0002: Member 'Umbraco.Commerce.PaymentProviders.Worldpay.WorldpayBusinessGateway350Settings.InstallId.set' exists on [Baseline] lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll but not on lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll [/home/vsts/work/1/s/src/Umbraco.Commerce.PaymentProviders.Worldpay/Umbraco.Commerce.PaymentProviders.Worldpay.csproj]
/opt/hostedtoolcache/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets(37,5): error CP0002: Member 'Umbraco.Commerce.PaymentProviders.Worldpay.WorldpayBusinessGateway350Settings.Capture.get' exists on [Baseline] lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll but not on lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll [/home/vsts/work/1/s/src/Umbraco.Commerce.PaymentProviders.Worldpay/Umbraco.Commerce.PaymentProviders.Worldpay.csproj]
/opt/hostedtoolcache/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets(37,5): error CP0002: Member 'Umbraco.Commerce.PaymentProviders.Worldpay.WorldpayBusinessGateway350Settings.Capture.set' exists on [Baseline] lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll but not on lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll [/home/vsts/work/1/s/src/Umbraco.Commerce.PaymentProviders.Worldpay/Umbraco.Commerce.PaymentProviders.Worldpay.csproj]
/opt/hostedtoolcache/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets(37,5): error CP0002: Member 'Umbraco.Commerce.PaymentProviders.Worldpay.WorldpayBusinessGateway350Settings.TestMode.get' exists on [Baseline] lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll but not on lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll [/home/vsts/work/1/s/src/Umbraco.Commerce.PaymentProviders.Worldpay/Umbraco.Commerce.PaymentProviders.Worldpay.csproj]
/opt/hostedtoolcache/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets(37,5): error CP0002: Member 'Umbraco.Commerce.PaymentProviders.Worldpay.WorldpayBusinessGateway350Settings.TestMode.set' exists on [Baseline] lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll but not on lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll [/home/vsts/work/1/s/src/Umbraco.Commerce.PaymentProviders.Worldpay/Umbraco.Commerce.PaymentProviders.Worldpay.csproj]
/opt/hostedtoolcache/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets(37,5): error CP0002: Member 'Umbraco.Commerce.PaymentProviders.Worldpay.WorldpayBusinessGateway350Settings.VerboseLogging.get' exists on [Baseline] lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll but not on lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll [/home/vsts/work/1/s/src/Umbraco.Commerce.PaymentProviders.Worldpay/Umbraco.Commerce.PaymentProviders.Worldpay.csproj]
/opt/hostedtoolcache/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets(37,5): error CP0002: Member 'Umbraco.Commerce.PaymentProviders.Worldpay.WorldpayBusinessGateway350Settings.VerboseLogging.set' exists on [Baseline] lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll but not on lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll [/home/vsts/work/1/s/src/Umbraco.Commerce.PaymentProviders.Worldpay/Umbraco.Commerce.PaymentProviders.Worldpay.csproj]
/opt/hostedtoolcache/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets(37,5): error CP0001: Type 'Umbraco.Commerce.PaymentProviders.Worldpay.Helpers.Md5Helper' exists on [Baseline] lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll but not on lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll [/home/vsts/work/1/s/src/Umbraco.Commerce.PaymentProviders.Worldpay/Umbraco.Commerce.PaymentProviders.Worldpay.csproj]
/opt/hostedtoolcache/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ApiCompat.ValidatePackage.targets(37,5): error CP0001: Type 'Umbraco.Commerce.PaymentProviders.Worldpay.Helpers.VerboseLoggingHelper' exists on [Baseline] lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll but not on lib/net6.0/Umbraco.Commerce.PaymentProviders.Worldpay.dll [/home/vsts/work/1/s/src/Umbraco.Commerce.PaymentProviders.Worldpay/Umbraco.Commerce.PaymentProviders.Worldpay.csproj]
```

**Comment by PeterKvayt** [comment]
Hi @umbracotrd!

I fixed the pipeline.
Could you please review pr and merge it?
If all will going well, then how long it take to release new version for v10?

**Comment by umbracotrd** [comment]
Thanks @PeterKvayt.

I've pushed `10.0.2--preview.2+2cdaf70` to [Umbraco prerelease and nightly feed](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/installing-nightly-builds). Please check it out if possible. We're having a hard time getting a test account from worldpay so we're unable to test it ourself.

Once you confirm, you can expect to see the `10.0.2` on Nuget in less than 24 hours. After that I'll cherry pick this PR to later versions.

**Comment by umbracotrd** [comment]
Hi @PeterKvayt, I made a mistake when bumping this package's version. Anyway, I've merged and pushed this PR to version `10.0.1`.
It should be searchable on nuget in couple minutes.

**Pull request merged**
